### ISSUE TITLE
Add support for DelegatingHandler

### ISSUE THREAD

**Issue by qetza** [AzureAD/microsoft-identity-web#1131]
**Is your feature request related to a problem? Please describe.**
Currently for using Microsoft.Identity.Web when calling APIs you have to use `IDownstreamWebApi` or do it manually through  `ITokenAcquisition`. This can be complicated/time consuming for existing applications.

**Describe the solution you'd like**
It would be a good solution to provide a DelegatingHandler which would use `ITokenAcquisition` to get a token and inject it in the Authorization HTTP headers. This way you only have to update your Startup class where you register your HTTP clients.
This can also benefit for teams that prefer managing all HTTP connection transversal topics through DelegatingHandler (Polly...).

**Describe alternatives you've considered**

**Additional context**
I've already discuss this with Jean-Marc and as I have a basic implementation done I will send PR.

**Comment by jmprieur** [comment]
The options to call an API would then because:
- If you want to use Microsoft Graph, inject `GraphServiceClient`
- If you want to call a REST API handling Json and don’t have an SDK, use `IDownstreamWebApi`
- If you are using an SDK:
  - If this is an Azure SDK, use the `TokenAcquisitionTokenCredential` which was introduced in 1.9
  - If this is another SDK that takes an Http delegate handler, then use a (new class to be provided) `TokenAcquisitionDelegateHandler`
  - If this is another SDK that requires a token, just use `ITokenAcquisition`.

**Comment by qetza** [comment]
Any idea when the PR will be included and released?

**Comment by jennyf19** [comment]
Included in [1.15 release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/1.15.0)
