### ISSUE TITLE
[Bug] AccessDenied Routing

### ISSUE THREAD

**Issue by mattosaurus** [AzureAD/microsoft-identity-web#117]
**Which Version of Microsoft Identity Web are you using ?**
Microsoft.Identity.Web - v0.1.0 Preview
Microsoft.Identity.Web.UI - v0.1.0 Preview

**Where is the issue?**
* Web App
    * [x] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (Validating tokens)
    * [ ] Protected web APIs (Validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In Memory caches
     * [ ] Session caches
     * [ ] Distributed caches

**Is this a new or existing app?**
c. This is a new app or experiment

**Repro**

Clone and run the below sample project.

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-2-Groups

Log in with an unauthorized account.

**Expected behavior**
Unauthorized account should be redirected to /MicrosoftIdentity/Account/AccessDenied.

**Actual behavior**
Unauthorized account is redirected to /Account/AccessDenied which doesn't exist.

**Possible Solution**
The Microsoft.Identity.Web.UI AccountController exists in the MicrosoftIdentity area but there doesn't seem to be a way to provide the AccessDenied response with this route info.

I'd expect this to be configurable using something like the AccessDenied property like this but it doesn't seem to work.

```
services.Configure<OpenIdConnectOptions>(options =>
{
	// Use the groups claim for populating roles
	options.TokenValidationParameters.RoleClaimType = "groups";
	options.AccessDeniedPath = "/MicrosoftIdentity/Account/AccessDenied";
});
```

Possibly this is a redirect URL that should be set in the portal but it's not obvious where this is.

A workaround is to create an account controller with the required view but this goes against the point of Microsoft.Identity.Web.UI.

**Comment by jmprieur** [comment]
@mattosaurus 

as a work around you could specify your page yourself doing the following:

public void ConfigureServices(IServiceCollection services)
{
    services.AddSignIn(Configuration);
    services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme,
        options => {
         	// Use the groups claim for populating roles
	       options.TokenValidationParameters.RoleClaimType = "groups";
	       options.AccessDeniedPath = "/MicrosoftIdentity/Account/AccessDenied";
        });

    // More code here ...
}

**Comment by jmprieur** [comment]
## Spec

### Why?

See issue above

### What? 

When using .AddMicrosoftIdentityUI, we should override the AccessDeniedPath to be  "/MicrosoftIdentity/Account/AccessDenied"

**Comment by creativebrother** [comment]
services.AddSignIn(Configuration, "AzureAd");
JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                // Use the groups claim for populating roles
                options.TokenValidationParameters.RoleClaimType = "roles"; 
                options.AccessDeniedPath = "/MicrosoftIdentity/Account/AccessDenied";
            });
work around by specifying AccessDeniedPath seems not working either for this  0.1.2-preview.

**Comment by pmaytak** [comment]
Yes, seems like specifying `AccessDeniedPath` on `OpenIdConnectOptions` doesn't work.

Specifying the path on `CookieAuthenticationOptions` works:
```csharp
services.Configure<CookieAuthenticationOptions>(CookieAuthenticationDefaults.AuthenticationScheme, options => {
    options.AccessDeniedPath = new PathString("/MicrosoftIdentity/Account/AccessDenied");
});
```
The scheme has to be the same as what is passed into `AddSignIn` method (or default `CookieAuthenticationDefaults.AuthenticationScheme`) because that is what is passed in https://github.com/AzureAD/microsoft-identity-web/blob/4458dbf15ddf494c2f3f5a27da873260bbe71040/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L82


From logging we can see that when the user is unauthorized and the code above is not used, cookie and OIDC handlers fail and redirect to `/Account/AccessDenied...` is done.
![image](https://user-images.githubusercontent.com/34331512/81779930-7ebeb500-94aa-11ea-85cf-d819bb565292.png)

When the above fix is used, after the handlers fail to authorize, the redirect is made to a correct page.
![image](https://user-images.githubusercontent.com/34331512/81779943-85e5c300-94aa-11ea-8473-b9924f16b8f0.png)

I looked through the ASP.NET Core repo and really the only references to `AccessDeniedPath` I found were related to cookies.

The default path value is in [CookieAuthenticationDefaults](https://github.com/dotnet/aspnetcore/blob/919451b7caeab0d47be5cb24dbc6e3f52d675b2c/src/Security/Authentication/Cookies/src/CookieAuthenticationDefaults.cs#L39).

If the custom path is not specified, it is set to default in [PostConfigureCookieAuthenticationOptions PostConfigure](https://github.com/dotnet/aspnetcore/blob/919451b7caeab0d47be5cb24dbc6e3f52d675b2c/src/Security/Authentication/Cookies/src/PostConfigureCookieAuthenticationOptions.cs#L55).

`CookieAuthenticationHandler` builds the URI and redirects in [HandleForbiddenAsync](https://github.com/dotnet/aspnetcore/blob/919451b7caeab0d47be5cb24dbc6e3f52d675b2c/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L420).

**Comment by jmprieur** [comment]
Thanks for investigating, @pmaytak 
Do you want to propose a fix?

**Comment by creativebrother** [comment]
So by default CookieAuthenticationHandler will be called even though if one does not use cookieauthentication scheme explicitly within asp.net core?

**Comment by pmaytak** [comment]
Well the `AccessDeniedPath` seems to be used from the scheme that was assigned to 
`OpenIdConnectOptions.SignInScheme` in `AddSignIn` method, which in our case is the cookie scheme.
https://github.com/AzureAD/microsoft-identity-web/blob/35a76fd2557b101e21cd6aef8ea99bffba6e80c7/src/Microsoft.Identity.Web/WebAppAuthenticationBuilderExtensions.cs#L85
I reckon cookie handler will only be called if cookie scheme is enabled.

**Comment by jennyf19** [comment]
In [0.1.4-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.4-preview)
