### ISSUE TITLE
ADB2C SSO giving ASPNETCORE ENV error when trying to sign in. [Bug] 

### ISSUE THREAD

**Issue by KurtDebzz** [AzureAD/microsoft-identity-web#1213]
**Which version of Microsoft Identity Web are you using?**

Microsoft Identity Web 1.1.0

**Where is the issue?**
* Web app
    * [X] Sign-in users
    * [ ] Sign-in users and call web APIs
* Web API
    * [ ] Protected web APIs (validating tokens)
    * [ ] Protected web APIs (validating scopes)
    * [ ] Protected web APIs call downstream web APIs
* Token cache serialization
     * [ ] In-memory caches
     * [ ] Session caches
     * [ ] Distributed caches
* Other (please describe)

**Is this a new or an existing app?**

This is a new app or an experiment.

I have been experimenting with ADB2C using .NET Core, in order to implement it in our company's future products, however, I came across this issue. I mistakenly misconfigured my app so that it uses Auth Code Flow without ticking the **ID Token / Access Token** from the portal, and obviously, it didn't work. What is confusing about this is that I was getting redirecting by **/signin-oidc** endpoint to an error page which is managed by **Microsoft Identity Web** - **/MicrosoftIdentity/Account/Error*. The error that was displayed by this error page is completely misleading and I spent hours debugging both my application and Azure's configuration before I eventually found out what the problem is.

The error that was being displayed is:
![image](https://user-images.githubusercontent.com/26603784/119521494-7a92cc00-bd7b-11eb-9b58-96b2122db965.png)

When I checked the **launchsettings.json**, everything was set-up correctly, as it can be seen below:

```csharp
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:21020",
      "sslPort": 44330
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      }
    },
    "WebApplication3": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
      },
      "dotnetRunMessages": "true",
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```
I was able to view the actual issue by going to my **Network** and in the form data being passed by the **signin-oidc** endpoint, there was an exception that was being thrown by ADB2C itself.

![Signin-oidc](https://user-images.githubusercontent.com/26603784/119523168-d447c600-bd7c-11eb-80bb-67aa77e8ce2c.png)

**Expected behavior**
I expected that the error message would be clearly explained by ADB2C instead of it being hidden the way it is currently. I understand that this might be a security concern, however, the error message does not help in identifying what the issue is. So something along the lines of "An ADB2C configuration exception has occurred" would have been a great help here.

**Actual behavior**
An incorrect error is being displayed instead.

Error:
**An error occurred while processing your request.
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.
Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application.**

Is there something that could have been done from my end or is this simply an issue, and if so are there any plans on this being fixed at any point?

**Comment by jennyf19** [comment]
@Tratcher suggestions on how we can improve this? If in development mode, the error message is clear, and the page can be overridden, but for a default, out-of-the-box, prod message, is there something better we can do?

**Comment by Tratcher** [comment]
The production error page intentionally does not discuss implementation details like this for the reasons it says above. The error would have still been reported in the server logs though. The error page should mention checking the server logs before it recommends enabling development mode. I'll file an issue for that.

**Comment by KurtDebzz** [comment]
So if this happens again in the future, the error message should indicate that there was an issue from ADB2C or otherwise? And in what version should I expect this to work, please?

**Comment by jmprieur** [comment]
@Kuhnsta : in 1.12.0 (see Milestone)

**Comment by danielwgrech** [comment]
I think the actual problem here is that the page reported by @KurtDebzz is displayed even when the environment is "Development".  It's like the same message is always displayed, regardless whether the environment is Development or Production.  It does not seem to be reading the ASPNETCORE_ENVIRONMENT value correctly.

**Comment by jennyf19** [comment]
@danielwgrech I don't see it when in Development, only when in Production. Both web app and web API need to be in Development in the launch settings. Can you share yours where you are able to repro this? Regardless we'll still update the error message. thx.

**Comment by danielwgrech** [comment]
@jennyf19 can you please share a screenshot of what you see instead of that page when you have a Development environment?  Also, any easy hint on how to screw up our ADB2C integration on purpose to generate the issue?  @KurtDebzz will be sharing the sample project once he manages to regenerate the issue.  Thanks!

**Comment by KurtDebzz** [comment]
@jennyf19 I have been able to generate this issue by inserting an incorrect **ClientSecret** value in my appsettings.json file. This had the same behavior as the one explained above with the sole difference that no error message was being sent in the form data of the **/signin-oidc** endpoint.

launchSettings.json
![image](https://user-images.githubusercontent.com/26603784/120437728-bc75d080-c380-11eb-8837-8f0793abdaeb.png)

Error page - Url: **localhost/MicrosoftIdentity/Account/Error**
![image](https://user-images.githubusercontent.com/26603784/120437870-e929e800-c380-11eb-894e-eef9e6a0c2b8.png)
![image](https://user-images.githubusercontent.com/26603784/120437977-0f4f8800-c381-11eb-9abf-2023049e2648.png)
![image](https://user-images.githubusercontent.com/26603784/120438001-18405980-c381-11eb-98c1-de9f3d9004e6.png)

You can also view this project by going to https://github.com/KurtDebzz/ADB2CWebApp.

**Comment by jmprieur** [comment]
@jennyf19 I'll leave this one open for the moment.

**Comment by jmprieur** [comment]
@Tratcher : do you have any idea?

**Comment by Tratcher** [comment]
Are they hitting this code path?
https://github.com/AzureAD/microsoft-identity-web/blob/bba91c4298411e780c9f082e8e3843eacd8e543c/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L95

**Comment by KurtDebzz** [comment]
Any updates on this, please?

**Comment by Ponant** [comment]
@Tratcher , yes

**Comment by Tratcher** [comment]
The ILoginErrorAccessor used to flow that message to the error page is somewhat complicated.
https://github.com/AzureAD/microsoft-identity-web/blob/bba91c4298411e780c9f082e8e3843eacd8e543c/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L93-L95
https://github.com/AzureAD/microsoft-identity-web/blob/272910102044a99815d1a70fea925cf3939b9b4d/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Pages/Account/Error.cshtml#L17-L21
https://github.com/AzureAD/microsoft-identity-web/blob/272910102044a99815d1a70fea925cf3939b9b4d/src/Microsoft.Identity.Web.UI/Areas/MicrosoftIdentity/Pages/Account/Error.cshtml.cs#L43
It also requires ITempDataDictionaryFactory
https://github.com/AzureAD/microsoft-identity-web/blob/0e8a08d8c55edf3aec695a809d189d2ac4b770d9/src/Microsoft.Identity.Web/WebAppExtensions/MicrosoftIdentityWebAppAuthenticationBuilderExtensions.cs#L251-L265
https://github.com/AzureAD/microsoft-identity-web/blob/0e8a08d8c55edf3aec695a809d189d2ac4b770d9/src/Microsoft.Identity.Web/TempDataLoginErrorAccessor.cs#L24-L31

ITempDataDictionaryFactory isn't registered unless you're using MVC
https://github.com/dotnet/aspnetcore/blob/b849efe77a282c4fd0baf460d68142d89a1b874d/src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L259
https://github.com/dotnet/aspnetcore/blob/b849efe77a282c4fd0baf460d68142d89a1b874d/src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L49

And the default implementation depends on cookies which can be temperamental in a sign-on flow due to issues like SameSite.
https://github.com/dotnet/aspnetcore/blob/b849efe77a282c4fd0baf460d68142d89a1b874d/src/Mvc/Mvc.ViewFeatures/src/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L249
https://github.com/dotnet/aspnetcore/blob/b849efe77a282c4fd0baf460d68142d89a1b874d/src/Mvc/Mvc.ViewFeatures/src/CookieTempDataProviderOptions.cs#L21-L26

**Comment by Ponant** [comment]
The PR https://github.com/AzureAD/microsoft-identity-web/pull/1468 allows in version 1.18.0 to define an `Microsoft.IdentityOptions.ErrorPath` to override `/MicrosoftIdentity/Account/Error`. The same for an `ResetPasswordPath`.
It does not solve this issue completely , but it should help in decoupling the UI library from the Web one.
