### ISSUE TITLE
Implement C# 8.0 nullable standard

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#15]
from @sujayvsarma and copied from https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/249

Even if the project is not C# 8.0, consider implementing the `nullable` standard by suffixing `?` to all parameters and returns that may be `NULL`. 

This will be a breaking changing internal to the library & to consuming code. Therefore, consider publishing the changes only during a major cycle.

**Comment by bgavrilMS** [comment]
That would be very cool indeed and the best time to do it is before releasing. Happy to help with this one, should not be too hard. 

This blog describes the feature better https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/

To quote from the blog: 

`Libraries can accurately describe the null behavior of the APIs, in a way that is checkable in client code at the call site. This raises expressiveness on API boundaries so that everyone can get a handle on the safe propagation and dereferencing of nulls. Nobody likes null reference exceptions or argument-null exceptions! This helps you write the code right the first time, and avoid the sources of those exceptions before you even compile and run the code.`

**Comment by jennyf19** [comment]
@bgavrilMS or @pmaytak can you put this in the correct milestone please? not a breaking change. thx

**Comment by jennyf19** [comment]
Included in [0.2.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.2.0-preview)
