### ISSUE TITLE
Should the `preferred_username` claim be used for User.Identity.Name?

### ISSUE THREAD

**Issue by chris5287** [AzureAD/microsoft-identity-web#1567]
https://github.com/AzureAD/microsoft-identity-web/blob/5d73a59029ce86833fe6f3f982587a2a715b9f12/src/Microsoft.Identity.Web/AppServicesAuth/AppServicesAuthenticationInformation.cs#L195

Based on Microsoft's own documentation the `preferred_username` claim should not be used to identity a user and make authorization decisions, so is this really the best claim to populate User.Identity.Name field?

![image](https://user-images.githubusercontent.com/1552744/147084218-46e3d381-e20c-4ec7-a033-251cd921cf64.png)
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validate-the-user-has-permission-to-access-this-data

**Comment by bgavrilMS** [comment]
Internally Microsoft.Identity.Web and the underlying Microsoft.identity.Client library rely on the `tid` + `oid` claims to tell accounts apart. The "name" claim is for display purposes.

**Comment by chris5287** [comment]
Is this exposed in the User.Identity object anywhere or any guidance documentation provided?

I feel like this is a very easy hole to fall down when .NET devs are used to using User.Identity.Name to capture a user's unique identity to use in application profiles 😔

**Comment by jennyf19** [comment]
@chris5287 The Name claim is a display name and should never be used to make authorization decisions, because it's too generic and can be changed (it can be anything). You would want to use `User.GetMsalAccountId()` or roles or groups to make authorization decisions. See these [samples](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ) for details.
