### ISSUE TITLE
IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user

### ISSUE THREAD

**Issue by jsquire** [AzureAD/microsoft-identity-web#1568]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#26043](https://github.com/Azure/azure-sdk-for-net/issues/26043).

## Details

I have set 👍 

```csharp
HttpContext.User = ClaimsPrincipalFactory.FromTenantIdAndObjectId(tenantid,objectid);
```

but while getting token with `await _tokenAcquisition.GetAccessTokenForUserAsync(scope);` it throws error.
Inner exception message like 'No account or login hint was passed to the AcquireTokenSilent call'

Could you please help me in that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da47a33-a7c4-b9b1-ea3a-2affbd28f934
* Version Independent ID: 6ef44932-a58a-dffc-8110-aec362c9695c
* Content: [ClaimsPrincipalFactory.FromTenantIdAndObjectId(String, String) Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.claimsprincipalfactory.fromtenantidandobjectid?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Web/ClaimsPrincipalFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/ClaimsPrincipalFactory.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jennyf19** [comment]
@AABhatt can you provide a link to your code or share a repro? there are a lot of variables in play which could cause this. Are you a web app or a web API?

**Comment by AABhatt** [comment]
> @AABhatt can you provide a link to your code or share a repro? there are a lot of variables in play which could cause this. Are you a web app or a web API?

Hi @jennyf19 . Let me explain the things in detail. I want to get an notification when email arrives in user's mailbox. 

1. For that I have created one web app where user logs in user Azure AD credential
2. I created one Web api from where I subscribe and getting notification from Graph Api.
3. From web app I am calling web api to subscribe by passing token
4. In Web api, I subscribe for log in user's mailbox
5. Now my web api also have Listen method who listen for notification which I subscribe
6. So I am getting notification while new mail arrives, then to get further mail content I want to call graph api. But here I need token or identity for the user for whom notification arrives. (I cached subscribtionid and userid for that)
7. Now for this I am using HttpContext.User = ClaimsPrincipalFactory.FromTenantIdAndObjectId(tenantid,objectid);
and trying to get token with await _tokenAcquisition.GetAccessTokenForUserAsync(scope);
8. Now it throws exception An MsalUiRequiredException was thrown due to a challenge for the user

Hope this will be helpful to understand.

**Comment by jennyf19** [comment]
@AABhatt thanks for the details.

I think instead of the timer in this [example](https://github.com/AzureAD/microsoft-identity-web/wiki/get-token-in-event-handler), use your listen method, and instead of using this `LongRunningWebApiSessionKeyAuto`, you can use the subscriptionId + userId, or whatever you want.

**Comment by AABhatt** [comment]
@jennyf19  Thanks for your providing information on that. But I doubt when Web API restart, would Web Api retain identity of every users who created subscription. Could you please have suggestion on that?

**Comment by jmprieur** [comment]
@AABhatt : you can use any key that makes sense to you.
When the web API restart, provided it has token cache serialization which is not in memory, this will work fine. See https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=aspnetcore

**Comment by MarcoEnxuto** [comment]
Hi, sorry for reopening this, but something is not right.
I checked the example told by @jennyf19 but i don't understand how you can get a token from cache without the 2 required paramers (objectId and TenantId).
I have a similar implementation like @AABhatt described, with the diference i have distributed cache with 2 levels. Memory cache and a database cache.
I have the exact same problem, when i try to retrieve an object from cache it raises the same error.
Quite doubtfull because i provide an user context which i prevously recorded while the user was subscribing to Graph. 
A little more detail:
I'm saving the TenantId, ObjectId and SubscriptionId (this one for managing purposes). I do this as i said, when the user is subscribing to Graph notifications.
When i receive a callback via Lifecycle endpoint, i try to obtain an access token from cache and interact later with Microsoft Graph by injecting the access token in the GraphServiceClient class.  The code breaks at the last line.

`...Code simplified for brevity....
HttpContext.User=ClaimsPrincipalFactory.FromTenantIdAndObjectId(tenantId,objectId);
string[] scope=new string[]{"access_as_user"};
AuthenticationResult result=await _tokenAcquisition.GetAuthenticationResultForUserAsync(scope,tenantId,null,User);
`
