### ISSUE TITLE
[Feature Request] On-Behalf-Of Flow in Azure B2C

### ISSUE THREAD

**Issue by mschaefer-gresham** [AzureAD/microsoft-identity-web#1994]
Can you confirm whether the On-Behalf-Of flow is supported in Azure B2C?

The [documentation](https://learn.microsoft.com/en-us/azure/active-directory-b2c/access-tokens) suggests it is not supported. And when I try to perform an on_behalf_of request in B2C:

```
dict["grant_type"] = "urn:ietf:params:oauth:grant-type:jwt-bearer";
dict["client_id"] = this.config.ClientId;
dict["client_secret"] = this.config.ClientSecret;
dict["assertion"] = accessToken;
dict["scope"] = scope;
dict["requested_token_use"] = "on_behalf_of";
var content = new FormUrlEncodedContent(dict);
var httpResponse = await httpClient.PostAsync(url, content);
```
I get the following error:

```
AADB2C99075: The feature On-Behalf-Of is not enabled for this tenant.
```

But using the token acquisition service like the following:

```
var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { scope });
```

appears to be doing a token exchange.

Is On-Behalf-Of flow is supported in Azure B2C, and if not, then what is GetAccessTokenForUserAsync doing and how is it different than On-Behalf-Of? And when will it be supported?

**Comment by svrooij** [comment]
It is **not supported** as stated [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/application-types#unsupported-application-types) and your can find a lot of other places where it says Azure AD b2c does not support on behalf of, because well, it’s not supported.

The code you’re referring to is probably code that is used in the client that also authenticated the user. It has a session with Azure AD b2c and (if consented) is allowed to get addition tokens, using the regular interactive flow. So this code either redirects the user to the token endpoint or uses the refresh_token to get a new access token for another scope.

this code cannot be used in a scenario where the client sends an access token to an api which in turn requests a token for some other api using the on behalf of flow.

**Comment by mschaefer-gresham** [comment]
@svrooij thank you. Is there any alterative to the On Behalf Of flow that can be used exchange an access token for another (i.e. a downstream api access token) when using B2C?  I'm trying to implement the BFF (no-tokens-in-the-browser) pattern, but have an issue when the BFF token (id or access) expires. 

### Goal:
1. The SPA should only rely on a httponly cookie issued by a "BFF" server app. The SPA should have zero dependencies on any auth type libraries (and obviously no tokens).

1. The BFF server should handle login, acquire and manage tokens for itself, and be able to acquire tokens for downstream apis on behalf of the logged in user.

1.  When the BFF server token (id or access) expires, the BFF should be able to renew this token silently such that the SPA is not involved at all (not redirected to the idp), allowing the BFF to continue acquiring tokens for downstream apis.

1.  This should work for Azure B2C.

### Problem:
If I use Microsoft.Identity.Web, acquiring the downstream api access token fails when BFF server id token expires. There is no way to silently renew the BFF id token server-side without the SPA being redirect to Azure for re-authentication.

If I use Microsoft.AspNetCore.Authentication extensions (AddCookie, AddOpenIdConnect) together with Azure B2C, I cannot achieve the token exchange for the downstream api token because the on_behalf_of flow is not supported in B2C.

Do you know how I can solve this issue? Is it perhaps possible to use this approach?

```
var url = this.disco.token_endpoint;
var dict = new Dictionary<string, string>();
dict["grant_type"] = "urn:ietf:params:oauth:grant-type:token-exchange";
dict["client_id"] = clientId;
dict["client_secret"] = clientSecret;
dict["subject_token"] = accessToken;
dict["scope"] = scope;
dict["audience"] = apiAudience;
dict["requested_token_type"] = "urn:ietf:params:oauth:token-type:refresh_token";
```

Any help is appreciated.

**Comment by svrooij** [comment]
You know you're asking in the repo of such an authentication library you desire not to use?

We use MSAL in all our clients to have it request tokens from Azure AD (b2c) directly using the pkce flow for public clients. Any openid connect library supporting pkce (all of them I guess) would work if you don't want a dependency on the Microsoft version.

That is because the token has a lifetime of 1 hour and the client can renew. It can also get tokens for several api.

Why are you so strict on "no tokens in the client"? A session token is eventually the same. The browser saved something that can be used to access an API.
If you have a problem with the token lifetime or you want to invalidate it when the user presses a button you should check out [conditional auth context](https://learn.microsoft.com/en-us/azure/active-directory/develop/developer-guide-conditional-access-authentication-context).

**Comment by mschaefer-gresham** [comment]
Our SPA currently works by acquiring tokens in the browser. It is my understanding that this is no longer best practice. The SPA should only receive an httponly cookie (which is presumably safer than a token), and the BFF ( server ) should be the one acquiring and managing tokens. I am influenced by [Duende](https://duendesoftware.com/products/bff) among other sources.

I would like to solve this using Microsoft.Identity.Web. As I mentioned, this does work fine using Microsoft.Identity.Web up to the point when the id token expires. At that point I can no longer acquire downstream api access tokens unless the SPA gets redirected over to Azure to renew. But this redirection is disruptive to our users because it's unpredictable and can cause requests to fail. I would like to be able to do this silently on the server to preempt the expiration.

I'm just trying to figure out if Microsoft.Identity.Web can support this or not. And if not, then I'm looking for some advice on alternatives. 

Thank you for your time.

**Comment by svrooij** [comment]
The piece has some good points, I just don't see any big advantages of this approach (at this moment). I do see however the need for conditional auth context, where you can check for token correctness more often and doing step-ups (request better protected trusted device for instance) greatly helps. By requesting that the token includes the user IP, and checking it, you can make sure that the token is not used in an other location.

Back to some pointers

It sounds like you're actually just using the authentication code flow on your server?
If so, just request the offline scope and utilize the refresh token to renew your tokens.

**Comment by svrooij** [comment]
I cannot help you any further with this endeavor. Personally I don't see any reason why this would be more secure. And technically it just isn't supported.
So if you want to use Azure AD B2C you have to try something else. You might want to ask in the "prototype" project: "how do I configure it to automatically refresh expired access tokens if we use the widely accepted token refresh flow with the openid connect scope "offline"."?

**Comment by mschaefer-gresham** [comment]
Thank you.
