### ISSUE TITLE
Always invalid token

### ISSUE THREAD

**Issue by jessestr** [AzureAD/microsoft-identity-web#207]
I am just finished trying to implement this: https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API

Instead of using a WPF application I am using a Blazor WASM client.

I added the token to the outgoing requests to my .net core API but I always get a 401.

Blazor authenticates well and gets the token back, seems to be working fine but:

 - the audience has the wrong GUID
 - "scp" (scope) is missing, hence the token being invalid for usage

If I run the sample from the link mentioned above and decode the token I can see a correct AUD & SCP in the token. So it's probably something with my configuration in Blazor?

**Config in Blazor**

 ```
   // AD authentication
    builder.Services.AddMsalAuthentication(options =>
    {
        builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
        options.ProviderOptions.DefaultAccessTokenScopes.Add("api://xxx-xxxx-xxxx-xxxx/access_as_user");
    });

    builder.Services
           .AddHttpClient<IApiClient, ApiClient>(client => client.BaseAddress = _baseUri)
           .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

```

**Response**

  `  Bearer error="invalid_token", error_description="The audience '63ee4227-xxxx-xxxx-xxxx' is invalid"
`

The audience GUID is the clientID of my Blazor app registration

**Code in Startup.cs**
```

    ...
    services.AddProtectedWebApi(Configuration)
            .AddInMemoryTokenCaches();
    ...

    ...
    app.UseAuthentication(); 
    app.UseAuthorization();
    ...

```

Any idea what could have been wrong?

**Comment by jennyf19** [comment]
@jessestr Does the scope value match the clientId of the web api and is it registered in the portal? 
something like `api://63ee4227-xxxx-xxxx-xxxx/access_as_user` 
The audience of the access token is the protected resource (or the web api) as the access token is for that resource. Which is why you have to provide a scope, as the access token is scoped to the permissions the user consented to.

> The audience GUID is the clientID of my Blazor app registration

This audience GUID should match that of the .net core api, not the client app.

The user authenticates using Blazor and you get back an access token, but the token is not valid because the audience is not right and there are no scopes, so when the .net core api (or protected resource) goes to validate the claims in the access token, it says "this token is not valid, the audience is wrong. it's not meant for me". and get you get a 401. More info on [registering a web api with azure](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad#register-an-application-in-azure-ad-to-represent-the-api). does this help?

**Comment by jmprieur** [comment]
Closing as it was answered
