### ISSUE TITLE
Question: will Microsoft Identity Web manage refresh tokens?

### ISSUE THREAD

**Issue by simonziegler** [AzureAD/microsoft-identity-web#221]
Hi, I'm working in Blazor (Server atm and Webassembly in the future) and use Azure B2C for authentication and authorization against ASP.NET web api servers. I expect to migrate to Microsoft Identity Web upon its release and wonder if MIW will manage refresh tokens? Specifically I want to follow [advice that I received](https://github.com/dotnet/AspNetCore.Docs/issues/18735#issuecomment-646356809) that my Blazor apps should not be using refresh tokens, rather the web api server should do this for them. So the heart of the question is whether MIW will do that, or will I need to hand crank this? Thanks!

**Comment by jennyf19** [comment]
@simonziegler Microsoft Identity web does manage refresh tokens as it provides token cache serialization.

**Comment by simonziegler** [comment]
Thank you! Is there any chance you might be able to point me in the direction of the relevant example code (noting that I've probably already been staring at it for a while...)?

**Comment by TheXenocide** [comment]
Is it just me or does it feel like this question was never actually answered? Maybe the question wasn't fully understood? Not really sure why this was closed.

**Comment by jmprieur** [comment]
Sorry @simonziegler @TheXenocide. I had not realized this wasn't clear enough.
1. If you use, a blazor server app, then this is like a web app, and the token are refreshed
   
   `dotnet net blazorserver --auth IndividualB2C`  --called-api-url xxx --called-api-scopes yyy

 2. If you use a blazorwasm hosted application you create a SPA + a Web API.
   
   `dotnet net blazorwasm --hosted --auth IndividualB2C`  --called-api-url xxx --called-api-scopes yyy
  
  1. the client part does not use refresh tokens.
  2. The Server part (the web API) can handle refresh tokens, unfortunately, Azure AD B2C does not support the on-behalf-of flow that is required for a web API to call a downstream web api. So this would work if --auth was SingleOrg, but not with IndividualB2C.

So the answer is:
- yes Microsoft.Identity.Web supports refresh tokens
- but you should keep using a blazor server app, because you authenticate with B2C.

**Comment by TheXenocide** [comment]
Thanks for the clarification; I'll move the rest of my quest for knowledge to the other question.
