### ISSUE TITLE
[Documentation] OWIN and .NET Framework Wiki

### ISSUE THREAD

**Issue by JaredShaver** [AzureAD/microsoft-identity-web#2228]
### Documentation related to component
OWIN/.NET Framework

### Please check all that apply

- [ ] typo
- [X] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue
Currently, the wiki documentation for OWIN and .NET Framework apps is hidden under https://github.com/AzureAD/microsoft-identity-web/wiki/v2.0 which is not very discoverable to a new user.  Please consider adding a wiki page with a link in the TOC to serve as the base for all specific details pertaining to using Identity.Web with OWIN and .NET Framework.

**Comment by jmprieur** [comment]
Thanks @JaredShaver. It's in progress (a PR is in progress for docs.micrsosft.com articles)

**Comment by JaredShaver** [comment]
@jmprieur any update on the documentation?

**Comment by jmprieur** [comment]
@JaredShaver:
sorry, I should have come back to you. This has been available since May from https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration?tabs=aspnet and the subsequent articles for web apps,
and https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnet for web APIs.
