### ISSUE TITLE
ManagedIdentityClientAssertion gets the wrong MSI token on non public clouds

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-identity-web#2749]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.17.4

### Web app

Sign-in users

### Web API

Protected web APIs (validating tokens)

### Token cache serialization

In-memory caches

### Description

The MSI FIC token is normally requested for the resource `api://AzureADTokenExchange`. It turns out that for other clouds, this magic string is different: 

Fairfax: `api://AzureADTokenExchangeUSGov`
Mooncake: `api://AzureADTokenExchangeChina`

Sadly for some air-gapped clouds it's also different and that cannot be hardcoded in MSAL / Id.Web; Even for sovereign clouds we should not hardcode cloud aliases, as these change over time.

### Reproduction steps

Try FIC in Mooncake.

### Relevant code snippets

```csharp
https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs
```

### Expected behavior

We need to provide a devex where app developers can configure this magic string. MSAL should hide this in public cloud.

**Comment by bgavrilMS** [comment]
CC @jmprieur @jennyf19

**Comment by jmprieur** [comment]
@kellyyangsong:
We need:
- A new property `string ? TokenExchangeUrl` for instance [here](https://github.com/AzureAD/microsoft-identity-abstractions-for-dotnet/blob/f854c43ae2361c3b6d424a8c8bdc20b61913fb2d/src/Microsoft.Identity.Abstractions/ApplicationOptions/CredentialDescription.cs#L300). This property can be null (will be null by default).
-  We'd use it [here](https://github.com/AzureAD/microsoft-identity-web/blob/256bf5edafc555756621151435661e11946986ce/src/Microsoft.Identity.Web.Certificateless/ManagedIdentityClientAssertion.cs#L47) if it's not null, and otherwise `api://AzureADTokenExchange`

Of course you'd need to add a parameter to the constructor, and use it in the CredentialLoader
