### ISSUE TITLE
GetTokenAcquirer cannot set SendX5C

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/microsoft-identity-web#2887]
### Microsoft.Identity.Web Library

Microsoft.Identity.Web

### Microsoft.Identity.Web version

2.19.0

### Web app

Not Applicable

### Web API

Not Applicable

### Token cache serialization

Not Applicable

### Description

As a user of 

https://github.com/AzureAD/microsoft-identity-web/blob/77df2a63d759beb5bbeb9c1260c8efdffd9fff94/src/Microsoft.Identity.Web.TokenAcquisition/DefaultTokenAcquirerFactoryImplementation.cs#L57

I have no way to set SendX5C to true.

### Reproduction steps

1. Try to use GetTokenAcquirer where sending the x5c header is required.

### Relevant code snippets

```csharp
GetTokenAcquirer(myOptionsWithX5CAsTrue)
```

### Expected behavior

GetTokenAcquirer should support sending x5c

**Comment by bgavrilMS** [comment]
Is this a regression?

**Comment by bgavrilMS** [comment]
I don't think this is a regression as this never worked. Still, an important bug since SN/I is pretty much mandatory internally. 

The problem is that [Id.Web does not add X5C to the assertion](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.TokenAcquisition/TokenAcquisition.cs#L434), which is creates manually because this is how this protocol works. 

Here's an example of how [X5C should be added](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/LegacyPopTest.NetFwk.cs#L404). Well, there is probably easier way to inject X5C than using JSON, but this is to show where it is needed.

**Comment by bgavrilMS** [comment]
I am taking this over as I have worked on this area before.

**Comment by jennyf19** [comment]
https://github.com/AzureAD/microsoft-identity-web/releases/tag/3.1.0
