### ISSUE TITLE
[Documentation]: How obtain refresh_token and id_token?

### ISSUE THREAD

**Issue by AlexanderPaule** [AzureAD/microsoft-identity-web#336]
### Documentation related to component

Web API Tokens

### Please check all that apply

- [ ] typo
- [x] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [x] needs an example

### Description of the issue

Hi, can you provide a code example or documentation on how to obtain **id_token** and **refresh_token**?

In our company we are trying to use Microsoft.Identity.Web for the authentication based on Azure AD B2C.
We are using .Net Core 3.1 and the latest version of the library **Microsoft.Identity.Web 0.2.0**.

We spent much time to understand the correct configuration and are able to connect properly and get **access_token**, but at the moment we didn't find how can we have **id_token** and **refresh_token**.

This is the example of a controller that needs to return all tokens.
```csharp
public static class Scopes
{
	public const string ReadTest = "https://[TenantName].onmicrosoft.com/test/read_test openid offline_access";
}

[Authorize]
[Route("api-user")]
public class UserInfoController : Controller
{
	private readonly ITokenAcquisition _tokenAcquisition;

	public UserInfoController(ITokenAcquisition tokenAcquisition)
	{
		_tokenAcquisition = tokenAcquisition;
	}

	[HttpGet("tokens")]
	[AuthorizeForScopes(Scopes = new []{ Scopes.ReadTest })]
	public async Task<IActionResult> Tokens()
	{
		var accessToken = await _tokenAcquisition
			.GetAccessTokenForUserAsync(new []{ Scopes.ReadTest });

		return new JsonResult(new
		{
			IdToken = null,// How to obtain it?
			RefreshToken = null,// How to obtain it?
			AccessToken = accessToken
		});
	}
}
```
Thank you

**Comment by AlexanderPaule** [comment]
Hi,
Can you provide updates on this issue?

**Comment by jmprieur** [comment]
@AlexanderPaule 

May I ask you what your scenario is? Why do you need the IDToken, AccessToken and Refresh token? What are they used for? Indeed, ASP.NET Core and Microsoft.Identity.Web manage things for you. Maybe you want to provide a kind of architectural diagram so that we can help you chose the right and safe way of doing?

- It's a Web API, so you don't get an IDToken. Information about the user is available in the claims of the User (`HttpContext.User.Claims`).
- It's not a good practice to let the refresh token leave your application. It's available in the MSAL.NET token cache (MSAL.NET is used by Microsoft.Identity.Web to acquire tokens, and `GetAccessTokenForUserAsync` will use automatically it when the access token needs to be refreshed.

Aside:
- In the scopes you declare (`ReadTest`), you don't need to declare `openid` and `offline_access`, they are automatically added by MSAL.NET


> We spent much time to understand the correct configuration 

What can we do to make the experience better? Did you have a look at the samples? https://github.com/AzureAD/microsoft-identity-web/wiki/web-api-samples ?

**Comment by AlexanderPaule** [comment]
Hi @jmprieur 

Thank you for the answer, now it is more clear.

The code I posted is only an example, don't look at it as a production code.
Our use case is not to expose the tokens outside the application.

The exact scenario we need is to call a web API from the web app and the reason why I opened the issue is:
-  **RefreshToken** required to refresh **AccessToken** - you said it is done automatically by the library, this is a very good news 👍
   In this case we don't need the refresh token.
- **IdToken** required in one particular case to authenticate the user when calling external web API.
   We encountered this scenario 3 years ago and to solve the problem we requested Microsoft support that get us this solution.
   We will test this scenario using **AccessToken** instead of **IdToken** and in case of troubles will open here a new issue.

For Aside suggestions, thank you very much, I'll fix our code.

For now you can close this issue.
Alex

**Comment by jmprieur** [comment]
Thanks for the update, @AlexanderPaule
