### ISSUE TITLE
[Feature Request] Allow to pass tenantId when requesting application access token

### ISSUE THREAD

**Issue by stvonolf** [AzureAD/microsoft-identity-web#413]
**Is your feature request related to a problem? Please describe.**
We would use a multi-tenant application which is authorized in several tenants. In each tenant, the application would be added in the Dynamics CRM as an app user. For each of those, we need to request the token using the tenant authority.

**Describe the solution you'd like**
Add tenantId parameter to GetAccessTokenForAppAsync - similar as in GetAccessTokenForUserAsync

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/TokenAcquisition.cs 

__

Addition. Given that for client credentials, we can only pass one scope (`resource/.default`), we'd want to change the signature to pass only one string (instead of a collection)

=> This is a breaking change. So proposing to take it (PM would say easy) in 0.3.0-preview
cc: @jennyf19 @henrik-me @pmaytak

**Comment by jmprieur** [comment]
@stvonolf how urgent is it for you?

**Comment by stvonolf** [comment]
If this is a use-case you want to support, it would be good to have it until the end of August if possible.

**Comment by stvonolf** [comment]
We should clarify first though, if requesting application tokens for multiple tenants is considered an anti-pattern.

**Comment by jmprieur** [comment]
Checked with @hpsin and here is what we agreed to:
- Change the signature of `GetAccessTokenForUserAsync` to take a `string` (instead of a `IEnumerable<string>`) as there is only one possible string for a given resource of App Id URI AppIdUri: "AppIdUri/.default". We can check that the resource ends in "./default"
- Add an additional optional parameter `tenant` to support this scenario, and verify that this tenant is not organizations (and of course common and consumers, which don't make sense)

**Comment by jmprieur** [comment]
Taking it as there is an API breaking change so I'd like it to be in 0.3.0-preview
