### ISSUE TITLE
Configuration sample without using MicrosoftIdentityUI

### ISSUE THREAD

**Issue by chriswill** [AzureAD/microsoft-identity-web#500]
I see how you've supplied the MicrosoftIdentity area, but I'd like to integrate the sign-in, sign-out, profile, etc within my own routes. I'm not sure how to configure the project so that I can supply the appropriate route values.  Is it the action for Microsoft.AspNetCore.Authentication.AuthenticationOptions? CookieAuthenticationOptions?

**Comment by pmaytak** [comment]
@chriswill I think in your view pages you would just specify your own routes. Like in [this sample](https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsMicrosoftGraph/Pages/Shared/_LoginPartial.cshtml#L9) you would point to your own sign in/out route. 
I think you can also configure similar paths in `CookieAuthenticationOptions', kind of like we do [here](https://github.com/AzureAD/microsoft-identity-web/blob/492b041167ef8fa33c80552202e5a9174724a10c/src/Microsoft.Identity.Web.UI/ServiceCollectionExtensions.cs#L34).

**Comment by chriswill** [comment]
Thanks @pmaytak. I've implemented CookieAuthenticationOptions, but don't think that's all there is to it.  For example, I intentionally induced an error by choosing the Run option on a Azure B2C user flow, and it automatically directed me to /MicrosoftIdentity/Account/Error.  I don't have a route there, so it just displayed the standard Error.cshtml page.

I was never a fan of the built-in IdentityUI area, but that's relatively easy to remove.  I hope this will be as well.

**Comment by pmaytak** [comment]
1. Just to be sure - I assume you don't call `.AddMicrosoftIdentityUI()` in `ConfigureServices` method right?
2. Based on your description, this might be a bug in AzureADB2COpenIDConnectEventHandlers because of hard-coded paths.
https://github.com/AzureAD/microsoft-identity-web/blob/492b041167ef8fa33c80552202e5a9174724a10c/src/Microsoft.Identity.Web/AzureADB2COpenIDConnectEventHandlers.cs#L72

As a workaround, you could try overwriting that code with something like this in `ConfigureServices`:
```csharp
services.Configure<OpenIdConnectOptions>(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
    options.Events.OnRemoteFailure = async context =>
    {
        //  Code that handles failure.
    };
});
```

@jennyf19 @jmprieur Thoughts?

**Comment by chriswill** [comment]
That's correct, I'm not calling .AddMicrosoftIdentityUI().

Thanks for the pointer on the events.  Those are very helpful.

**Comment by jennyf19** [comment]
closing as answered.
