### ISSUE TITLE
Is it possible to use Microsoft.Graph.Beta instead of Microsoft.Graph?

### ISSUE THREAD

**Issue by schmid37** [AzureAD/microsoft-identity-web#506]
Both Libraries are using the same namespaces… We have to use the Beta because of the new Intune fuctions and it produces reference errors.

Please evaluate if this is possible.

**Comment by schmid37** [comment]
@jmprieur how do you think Microsoft should handle this? The namespace in Microsoft.Graph and Microsoft.Graph.Beta are the same... We definatelly need the new functions of Microsoft.Graph.Beta to integration Win32Lob apps in intune. This is not possible with Microsoft.Graph. This is very inconsistent.

**Comment by jmprieur** [comment]
@darrelmiller: what would you suggest?
when would Intune be available in Graph v1.0 ?

**Comment by schmid37** [comment]
@jmprieur Intune Graph v1.0 is available since I think the beginning. The whole world is waiting for the release of the actual Beta 😆

**Comment by darrelmiller** [comment]
@schmid37   Microsoft.Graph.Beta is a superset of the Microsoft.Graph library so you could use the Microsoft.Graph.Beta library instead of Microsoft.Graph.  It would mean that your client is calling beta for all of the resources.  However, due to the fact that we don't allow breaking changes, calling the beta APIs would not likely cause issues.

The alternate approach to use `extern alias` to reference both assemblies even though they use the same namespace.  https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias

**Comment by schmid37** [comment]
@darrelmiller Thanks for the reply. We use the Microsoft.Graph.Beta for sure. Because we need to integrate Win32Lob apps in Intune. This is only possible with the beta. 

The question is, what impacts would @jmprieur have when they would use Microsoft.Graph.Beta instead of Microsoft.Graph?

An other question is, when will you find the consistency between Microsoft.Graph and Microsoft.Graph.Beta? Maybe through a release? Maybe through the possibility to provide previews within only **one** NuGet package? 

Nobody understands why there are two libraries with the same namespace. I don't know any company, we work with, which is amused about this situation. Companies which needs to integrate Win32Lob apps in Intune are reliant on using an beta... This is not really acceptable.

The alternate approach is a workaround with limits... So I already tried this and it won't really work with referenced projects in a solution.

**Comment by gavinmnz** [comment]
We're also encountering this issue as we're attempting to build an application using the Bookings API ahead of its official release, this is being done in conjunction with Microsoft NZ. We therefore need to use the Beta API but can't alongside this Auth library currently.

I note that on the original feature request that was added in 0.3.0-preview (#427) there were references to calling the Beta API however that doesn't appear to be achievable currently.

**Comment by jmprieur** [comment]
@schmid37 @gavinmn
Would that work for you if we splat Microsoft.Identity web into another NuGet package (for instance Microsoft.Identity.Web.MicrosoftGraph) to bring the MicrosoftGraph specific classes? 

We could then have two: 
- Microsoft.Identity.Web.MicrosoftGraph (Leveraging the MicrosoftGraph SDK)
- Microsoft.Identity.Web.MicrosoftGraphBeta (Leveraging the MicrosoftGraph SDK Beta SDK)

The ASP.NET Core template would use Microsoft.Identity.Web.MicrosoftGraph, but you/customers could substitute it with Microsoft.Identity.Web.MicrosoftGraphBeta?
The model would be the same as the Graph SDK (that is the same assemblies), which arguably is a bit weird indeed.

cc: @jennyf19 @darrelmiller @henrik-me @pmaytak

**Comment by schmid37** [comment]
@jmprieur sounds good to me. Hopefully not to forget that this is only a workaround. That would work for us. 

@darrelmiller is it possible to get a clear way with the Graph SDK? Will this case remain after .Net 5 release?

**Comment by jmprieur** [comment]
@gavinmnz  
> I note that on the original feature request that was added in 0.3.0-preview (#427) there were references to calling the Beta API however that doesn't appear to be achievable currently.

Unless I did not understand anything, you can always call the Graph beta endpoint (you change the BaseURL like [here](https://github.com/AzureAD/microsoft-identity-web/blob/875468f193d3a76d0e770a6568971f4b400928e3/tests/WebAppCallsMicrosoftGraph/appsettings.json#L12)) with the non-beta Graph SDK ?

**Comment by darrelmiller** [comment]
@jmprieur  We have an issue open for creating Microsoft.Graph.Web  https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/766.  We can also create Microsoft.Graph.Beta.Web.  The Microsoft Graph libraries should take a dependency on the Microsoft.Identity libraries, not the other way around.

@schmid37 Microsoft.Graph and Microsoft.Graph.Beta will always be different as long as we are continuing to develop Microsoft Graph.  New features are being added into Microsoft.Graph all the time and they go through a beta phase before moving to V1.  For this reason Microsoft.Graph.Beta will always be preview because the teams that build those APIs do not want customers to take a production dependency on those APIs unless the customer is prepared to accept breaking changes in production.

If there are Intune related APIs on Microsoft Graph that are in beta that you need to have in a production application, then the Intune team needs to hear about it.  It is the Intune team that make the decision about promoting APIs from beta to V1.0 when they are ready.  We on the Microsoft Graph Developer Experience team would be delighted to see those APIs move out of beta.

Regarding the multiple namespaces, that is an issue that I own and we had extensive discussions with customers on whether the two packages should have the same namespace or not.  I did not have any customers with strong feelings about them being in different namespaces.  I am open to hearing additional feedback on this.  We could add Microsoft.Graph.Beta namespace into the beta package, but we need to consider the consequences of that choice.

**Comment by schmid37** [comment]
@darrelmiller Thanks for the feedback! Seems to be logic. To be honest, it would be easier to deal with an explicit **Beta** namespace to know what you are using in the code itself. It's a mess when you have the Microsoft.Graph referenced from an external NuGet package, but your project uses the Microsoft.Graph.Beta. We are very open for solutions. Doesn't matter which way.
I think a good way is to open an issue in the microsoftgraph/msgraph-sdk-dotnet repo to have a transparent discussion with other customers.

**Comment by jmprieur** [comment]
@jennyf19 
@darrelmiller and I just synced and we propose to split Microsoft.Identity.Web into:
- P1/ Microsoft.Identity.Web (current, without the https://github.com/AzureAD/microsoft-identity-web/tree/master/src/Microsoft.Identity.Web/MicrosoftGraph folder)
- P1/ Microsoft.Identity.Web.MicrosoftGraph (only that MicrosoftGraph folder, references both Microsoft.Identity.Web and the MicrosoftGraph SDK)
- P2/ Microsoft.Identity.Web.MicrosoftGraph.Beta (only that MicrosoftGraph folder, references both Microsoft.Identity.Web and the MicrosoftGraph SDK Beta)

This way we allow the scenario that @schmid37 and @gavinmnz want.

Work to be done:
- create a new project, and a new NuGet package (no need to change the CI build)
- move the 3 files into that project (we can still keep the same namespaces)
- update our templates to reference the new NuGet package
- update the release definition to add pushing the new NuGet package
- Propose a PR for ASP.NET Core to add a reference to the new NuGet package. From their point of view this would not change anything else if we keep the same namespace.

cc: @pmaytak @henrik-me

**Comment by jennyf19** [comment]
Included in [0.4.0-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.4.0-preview)
