### ISSUE TITLE
Claims Enrichment

### ISSUE THREAD

**Issue by 3GDXC** [AzureAD/microsoft-identity-web#564]
Please provide an example where a web application may hook into the authorization flow and enrich the user claims token with additional user information for the applications own data source(s)

**Comment by jmprieur** [comment]
@3GDXC : what do you mean? Can you please explain your scenario?
Is it an example? (documentation not enhancement)? or do you wish to have something new in the API (enhancement)?

Did you read this article: https://github.com/AzureAD/microsoft-identity-web/wiki/customization ? which probably already explains it all?

**Comment by mslucasMMID** [comment]
or more information on [https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps](https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps)

**Comment by jmprieur** [comment]
@mslucasMMID : I still don't understand what the scenario is, and what you'd want? could you please elaborate? give an example?

**Comment by mslucasMMID** [comment]
I'm not the original poster. 
I use it because I want to insert a claim with a token/"specific info" to connect my local DB to the signin username. If I add the token during options.Events.OnTokenValidated I now the user is valid and I only have to lookup this specific info ones. 

But i'm a newbie so maybe there is a better way.

**Comment by jmprieur** [comment]
@3GDXC : were the links helpful?
Adding https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

Closing the issue. Reopen if you disagree.
