### ISSUE TITLE
[Feature Request] Use IGraphServiceClient when registering the service

### ISSUE THREAD

**Issue by SirRichie** [AzureAD/microsoft-identity-web#625]
**Is your feature request related to a problem? Please describe.**
DI should always use interfaces and not classes. Existing projects that have their constructors designed to depend on IGraphServiceClient currently fail to be properly constructed by .NET Core's DI as AddMicrosoftGraph() registers GraphServiceClient instead of the interface

**Describe the solution you'd like**
In Microsoft.Identity.Web.MicrosoftGraphExtensions::AddMicrosoftGraph replace 
builder.Services.AddScoped<GraphServiceClient, GraphServiceClient>(serviceProvider =>
with
builder.Services.AddScoped<**I**GraphServiceClient, GraphServiceClient>(serviceProvider =>

**Describe alternatives you've considered**
Alternatively, the registered GraphServiceClient needs to be obtained by constructing an intermediate ServiceProvider and the necessary classes manually instantiated.

**Comment by jmprieur** [comment]
@SirRichie I agree with you, however, we received a demand from the Graph SDK team to expose the GraphClientService and not the IGraphServiceClient
Adding @darrelmiller who can justify this guidance.

**Comment by darrelmiller** [comment]
Hi @SirRichie 

> DI should always use interfaces and not classes.

Would you be able to point me to that guidance?  I'm not aware of it, and when I polled the larger .NET community I did not get that feedback.

The GraphServiceClient gets updated regularly with new properties because Microsoft Graph regularly adds new endpoints.  If we were to define an interface that corresponds to the properties of Graph Service Client we would cause a breaking change to the interface when we make additive and non-breaking changes to Microsoft Graph.  This would mean that customers who actually implemented the interface that we defined, would regularly be broken for no useful reason.

I completely understand if you would prefer to access Graph services via an interface.  If so, I would encourage you to define an interface that exposes specifically the parts of Graph that your application calls.  You can then register an implementation of that interface that accepts GraphServiceClient into it's constructor.  Then you can test your controllers by injecting a fake version of that service.

**Comment by SirRichie** [comment]
Hi @darrelmiller 

> Would you be able to point me to that guidance? I'm not aware of it, and when I polled the larger .NET community I did not get that feedback.

In my experience (both practical and in various classes) DI is a form of / makes use of Inversion of Control, which in a nutshell means you should always program against interfaces. There is a [question on stackoverflow ](https://www.codeproject.com/Articles/538536/A-curry-of-Dependency-Inversion-Principle-DIP-Inve#Problems%20we%20will%20face%20if%20we%20do%20not%20maintain%20DIP)regarding this, [a very detailed article on codeproject](https://www.codeproject.com/Articles/538536/A-curry-of-Dependency-Inversion-Principle-DIP-Inve#Problems%20we%20will%20face%20if%20we%20do%20not%20maintain%20DIP) (specifically the chapter on DIP) and even [Microsoft's own documentation on DI in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)

The Microsoft Graph SDK already comes with a defined interface IGraphServiceClient which defines all the methods of GraphServiceClient (as it should be). So I assume the interface will always reflect changes in the class anyway, with all the consequences of updating your code.

I am more than happy to jump into a detailed discussion on this, although the provided sources make a very strong case in my opinion, especially regarding how easy it is to maintain your code when changes in libraries happen.

@jmprieur would it also be an option to register both the class and the interface? This would have almost no memory footprint (same instance) and allow for clients to choose freely between the two.

**Comment by darrelmiller** [comment]
@SirRichie The Graph Service library is full of interfaces because the original implementation followed the guidance that everything needs an interface to be tested.  Unfortunately that has caused the library to be significantly bloated with interfaces that are unnecessary and never used.  There is a misconception that interfaces are needed to do testing and it has unfortunate consequences.  Those interfaces, including the IGraphServiceClient, will be removed in our next major update to the service library.

Interfaces are useful when it is expected that there would be different implementations of some contract.   The only valid reason for having a different implementation of GraphServiceClient is to provide a fake for testing.  However, testing an application by trying to mock GraphServiceClient is not an effective solution.  Mocking GraphServiceClient requires mocking 
thousands of objects due to the method chaining approach used to construct requests.  It's just not a healthy thing to do.

In the C# world the convention is to always have an interface because the language is limited in it's ability to create mocks of concrete types.  Languages like F# and Java don't have this same dependency on interfaces to enable DI/IOC.  IOC is as much about object construction dependencies and lifetimes as it is about switching implementations.  

I don't recommend taking a dependency on the IGraphServiceClient as it will be removed.

You can see there are a wide range of opinions on this topic  https://twitter.com/darrel_miller/status/1250580226205245440  but you can also see there is plenty of precedent for registering concrete types.  

If you want to inject cross cutting concerns, use the middleware pipeline. If you want to inject fake HTTP responses use our ChaosHandler middleware.

**Comment by SirRichie** [comment]
@darrelmiller Fully agreed that an interface only makes sense if you're planning on being able to switch implementations. I guess the presence of the interface led me to believe the SDK team expected that at some point. 
Thanks for providing that insight and I guess this is the reason why the Identity.Web team was asked to switch to the concrete class.

**Comment by hadrian625** [comment]
I know this is closed, but I agree with what @SirRichie says. Having to code against a class implementation, instead of an interface causes problems that defeat the inversion of control principle. Also when trying to unit test your implementation one will always take into account the mocking is no longer an option (usually) and if you don't have mocking, your are no longer unit testing, but doing an integration test in regard to the dependency which in this case is GraphServiceClient

**Comment by jmprieur** [comment]
@hadrian625 : we are following the guidance from the Graph SDK people. Please discuss with them. I you manage to convince them, we'll definitively change this.
