### ISSUE TITLE
Add static analysis rules from asp.net core

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/microsoft-identity-web#76]
Add Roslyn analyzers packages to the projects.

**Comment by pmaytak** [comment]
@jennyf19 
Is this work item about adding FxCop to the build pipeline or to the project as a Nuget? Is there anything else to do besides that? Like copy ruleset from somewhere?

**Comment by bgavrilMS** [comment]
There is a requirement to run the security static analysis - smth like [this ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/aef655d4575d5c4849de9f8a1df0ff7ac38affe6/build/template-postbuild-code-analysis.yaml#L5)

Otherwise, you can just try to the default FxCop Roslyn analyzers from here (as a nuget package) https://github.com/dotnet/roslyn-analyzers

**Comment by pmaytak** [comment]
Yep, I think our builds are setup already. I added FxCop as a Nuget but was just wondering if we have any custom rules or default ones are fine. There's a [ruleset file](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/Microsoft.Identity.Web.ruleset) but it seems to be old.

**Comment by jennyf19** [comment]
included in [0.1.1-preview release](https://github.com/AzureAD/microsoft-identity-web/releases/tag/0.1.1-preview)
