### ISSUE TITLE
Logout from multiple tabs

### ISSUE THREAD

**Issue by vladop** [AzureAD/microsoft-identity-web#769]
Logout is very simple using:
      `  <a href="MicrosoftIdentity/Account/SignOut">Log out</a>`

However in Blazor server app with multiple tabs opened when user is logged out (he can still continue to use app (altough he gets message "Sucessfully logged out. It is good idea to close other browser window".

This seems wrong.
Also, why he need to choose account from which he need to logout (he is logged in only with one account)

**Comment by jmprieur** [comment]
@vladop : is it blazor server or Blazor web assembly (hosted or not)?
@javiercn  do you have an idea for the first question.

@hpsin: in https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-a-sign-out-request, I don't think we explain why the user needs to select the account to sign-out. Should we?

**Comment by vladop** [comment]
It is blazor server app.
Maybe it is not an issue that it has to choose account to signout altough I as (expirenced) user didn't expect that.
Issue is that I can go to another tab and to whatever I want (even make some requests to server, some destructive actions)
Once I refresh page, I get redirected to login screen which is ok but multiple tabs opened is problem in this case

**Comment by javiercn** [comment]
@jmprieur this is by design.

By default Blazor sets up the authentication context during the initial request to the page and maintains it for the lifetime of the Blazor server session (the circuit).

There is extensibility that can be used to implement your own mechanism for updating the authentication state for a given user. See [here](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Server/src/Circuits/RevalidatingServerAuthenticationStateProvider.cs) for details.

The main thing to understand is that there are no requests and responses going on from the browser to the server, so the app doesn't have a way to check that there is a cookie and that it is still valid. A revalidating provider would have to check for that.

**Comment by vladop** [comment]
Anyway, I think that just because Blazor works differently from other frameworks doesn't mean that it needs to introduce strange user experience and security risks. User that uses app once logged out doesn't seem reasonable by design or default behavior or something that average Joe as developer should "hack" into.
