### ISSUE TITLE
[Documentation] App Service Integration (X-MS-TOKEN-AAD-ACCESS-TOKEN is empty)

### ISSUE THREAD

**Issue by OnAzureCloud9** [AzureAD/microsoft-identity-web#775]
### Please check all that apply

- [ ] typo
- [ X] documentation doesn't exist
- [ X] documentation needs clarification
- [ ] error(s) in the example
- [ X] needs an example

### Description of the issue
As described in notes from a [recent release](https://github.com/AzureAD/microsoft-identity-web/wiki/1.2.0#integration-with-azure-app-services-authentication-of-web-apps-running-with-microsoftidentityweb) the library should now allow for Azure App Service auth integration. I had a working set of app registrations (one for front end and back end API) using Ms.Id.Web with no issues. After enabling App Service integration it's not working. I have also taken the additional step [described here](https://docs.microsoft.com/en-us/azure/app-service/tutorial-auth-aad?pivots=platform-windows#configure-app-service-to-return-a-usable-access-token) which adds additional login params.

Since both apps are running in Azure I added some logging to get some info on the issue. First I checked that `AppServicesAuthenticationInformation.IsAppServicesAadAuthenticationEnabled` is enabled and is true. That means the token acquisition service specifically for App Service is used. However, the `X-MS-TOKEN-AAD-ACCESS-TOKEN` header is always empty. The token acquisition service just returns an empty string so it's not very obvious. Then API calls to the backend just don't work since the access token is null.

Please provide some documentation if there are special requirements to get app registrations working with Ms.Id.Web and App Service.

**Comment by jmprieur** [comment]
@OnAzureCloud9: thanks for your feedback. There shouldn't be any requirements other than enabling authentication with the Azure AD IDP, and add the additional login params.

There is a new set of tutorials that you might want to have a look at: 
https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-overview

I guess this is the one you'd like to read: https://docs.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-user?tabs=command-line

In order to debug your issue, you might want to add to your application a Page (or a View) like this one: https://github.com/AzureAD/microsoft-identity-web/blob/master/tests/WebAppCallsMicrosoftGraph/Pages/Debugging.cshtml.
It displays the environment variables and the headers that are sent by Easy Auth (when your app is deployed).

cc: @navyasric 

Also, if your app was working without Easy Auth, I would not necessarily recommend that you turn it on (it's really for simple scenarios).

**Comment by jmprieur** [comment]
@navyasric : do you know who could help here?

**Comment by navyasric** [comment]
@OnAzureCloud9 Any update on the debugging on this issues? Agree with all that is mentioned by above my jmprieur. When adding additional login params, did you set the "resource" to the backend API's app ID? 
Let us know if you are  still having trouble getting access token from App service.

@mattchenderson Do you know any reason the App service would return an empty string in Access token header?

**Comment by jennyf19** [comment]
closing, but feel free to reopen @OnAzureCloud9 with the information @navyasric asked for above. thanks.
